language: node_js
node_js:
- lts/*
deploy:
  provider: npm
  email: email@slonoed.net
  api_key:
    secure: 2bIHLYS2e/oaOTG/7pPQhAmBKX8vqAsfGUM57h6UKNCf/xScqSNPbdjjOK+wfns+SbVausLt0tEsEaiIr1RpkNboZ0GhzIPSSXaRIi9EDboGJdAd6gBCIGZ/uw+cj3MUAKLwbrTFGpxIUzD7doy5TiFIXfzUZtWupbhCho8KI8cgVCv90varmOS/J5F4y5D5qJBr9I2boq4z9sh3R/d2vzbG7kpvsrlq8TTSkMO71IsJAAJGIknUXJjHuctJU4IjL3H48RW5RZTUpVDy74EuWhStBIKlhJrJuMsjX2srIesSi9LpCb3ReBN4yUFfs1hAKJ6NWNB4cUVa9FnIP3Xtvrh15OxpcKPgB7fB0PDErKPEX3KcKB6N+RHmyVtRz4cthl9GMI+rZjAEV0my1A68u6yY24EpwUvBQl4n4qgUOQgYWB+uXQtMZO+cvpMJQbFQ4kQR6BWe0W/3BwTrHq9gYVZCUSNHVfM1SwQA3uZFahr9CmU+oWyaD4Iy+xCQhGh8N7ncyItX6zn3Dni8SrkvJJ2BUAeWsIKngrmA+tjrcmhTSHH4PtXFegN6gv63+XjSWwG5CYBVq34P1W0NVHlT1J7/0n1FnMyBzxCbNMgKbvP9vL6rZ6OolurkT0BvmkUCKe0hGSc1BQgWm0qOHmSwIsTJvBym23tmaBUEBFXf1Fo=
  on:
    branch: master
    repo: slonoed/jsref
